# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_comment_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='contenido',
        ),
    ]
