# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20170929_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, validators=[posts.validators.validate_title]),
        ),
    ]
