# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20170929_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=120, validators=[posts.validators.validate_title]),
        ),
    ]
