# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_activation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=profiles.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
